### ISSUE TITLE
Enable usage of external kallisto/bustools installation

### ISSUE THREAD

**Issue by apeltzer** [pachterlab/kb_python#109]
**Describe the issue**

Hello! 

@FloWuenne and I ran into an issue when trying to use a Singularity containerized version of this, which results in some shared library issues. 

This is often the case, when precompiled binaries are shipped with the python package and is unfortunately true for the bioconda recipe for kb-python too. There is multiple things one could do:

a.) Patch around this, by simply patching out the kb-python function in `config.py` to "find" the linux/osx/windows binaries that are installed via bioconda
b.) allowing the `config.py` function to find / use externally managed bustools + kallisto versions too

I'm fairly thinking that b.) is the nicer option, but happy to be told otherwise - @dpryan79 and @Maarten-vd-Sande were also involved in some comments on this in the bioconda gitter, so I'm linking you in here too.

**Comment by apeltzer** [comment]
b.) could also be made in a way that allows "normal" users to run as before and more advanced ones who rely on installing the libraries e.g. in a container to assume that both tools are in the path. Would be a couple of lines of extra code without having to maintain patches.

**Comment by Lioscro** [comment]
Hi, @apeltzer,
I've also had this on my mind for some time now.
I was thinking adding an option to specify the command/path to a kallisto or bustools binary to use (instead of the provided one) with `--kallisto` or `--bustools` command-line arguments.

Would this work for your case?

**Comment by dpryan79** [comment]
The best implementation would be to make `--kallisto` and `--bustools` options truly optional and assume that the binaries are in your path unless they're specified.

**Comment by apeltzer** [comment]
As @dpryan79 is the more experienced here, this would be a good option I think - or a smart lookup functionality that simply checks for the existence of an external binary and if that fails uses the internal one?

**Comment by Lioscro** [comment]
> The best implementation would be to make `--kallisto` and `--bustools` options truly optional and assume that the binaries are in your path unless they're specified.

Yeah, exactly. The arguments would be optional, though I think the provided binaries should be the default if those arguments are not provided. 

Here is my proposed behavior.
* If `--kallisto` is provided, use that binary. Allow use of binaries in path, so if `kallisto` is a valid command, `--kallisto kallisto` would point to the binary in your path.
* Otherwise, use provided binary.
Same for `--bustools`.

**Comment by apeltzer** [comment]
Yup sounds good to me 👍🏻

**Comment by Lioscro** [comment]
@apeltzer @dpryan79 @Maarten-vd-Sande 
This has been implemented in 7f4ae6c364f65ebf96f0b911888ddc0aba6b1676 in `devel`. I've validated that it works on my end, but could some of you try it out as well?
If everything's working fine we can push a new release with these changes.
You can install from `devel` by running
```
pip instll git+https://github.com/pachterlab/kb_python@devel
```

**Comment by Lioscro** [comment]
All changes in the `devel` branch are planned to be merged on Monday, April 12th, if there aren't any issues. A new version will be released to Pypi shortly after.

**Comment by Maarten-vd-Sande** [comment]
@Lioscro I am currently implementing this on the bioconda side. Does it work with _any_ kallisto/bustools version? Or should I just pin the version you use now in kb-python? 

0.40.0 for bustools
0.46.2 for kallisto

**Comment by Lioscro** [comment]
> @Lioscro I am currently implementing this on the bioconda side. Does it work with _any_ kallisto/bustools version? Or should I just pin the version you use now in kb-python?
> 
> 0.40.0 for bustools
> 0.46.2 for kallisto

I didn't add a check for binary versions, but at a minimum `kallisto bus` should be implemented. Not sure when that was first introduced. (Additionally, `bustools mash` needs to be implemented for split indices.) To avoid the headache, I think it's fine to pin the versions to those included.
