### ISSUE TITLE
Handling of temporary directory

### ISSUE THREAD

**Issue by apredeus** [pachterlab/kb_python#119]
Dear kallisto team, 

I recently installed `kb-python` on one of the servers I work on, and ran the command that allows you to download the pre-build `kallisto` reference (`kb ref -d human -i human.idx -g human.t2g`)

To my surprise, the command completely wiped my /tmp folder. There was lots of useful files there... I guess it's deleting the folder after? It would be good if the program only delete the files it created by default, and not the whole folder.

**Comment by Lioscro** [comment]
Hi, @apredeus,
`kb` should be creating a `tmp` folder at the location where you ran the command, and remove this folder once it has finished. We haven't observed this behavior in testing.
Are you running the command in the root directory `/`?

**Comment by apredeus** [comment]
I've ran it in my home, just for the sake of quick test. So I guess it created a new /tmp and removed the existing one.

**Comment by Lioscro** [comment]
Yeah, that's probably what happened. I've pushed an update to `devel` so that `kb` prints an error when it finds an existing temporary directory, so that this won't be a problem in the future. Should be included in the next release.
Thanks for the report!
