### ISSUE TITLE
Error during mkref - gtf formatting?

### ISSUE THREAD

**Issue by Ruth-hals** [pachterlab/kb_python#121]
Hi! Thanks for replying in the other issue! Sorry I thought this was a similar problem...
I'm getting no output when trying to make the reference and the standard error output file contains the following msg:

> Error file output:
> [2021-04-30 18:16:03,940]    INFO Preparing genome.fa.gz, genes.gtf.gz
> [2021-04-30 18:16:03,940]    INFO Decompressing genome.fa.gz to tmp
> [2021-04-30 18:16:17,333]    INFO Sorting tmp/genome.fa to /lustre1/project/stg_00056/octopus/cellranger/kalbus/tmp/tmp6mhenrxr
> [2021-04-30 18:19:48,363]    INFO Decompressing genes.gtf.gz to tmp
> [2021-04-30 18:19:48,371]    INFO Sorting tmp/genes.gtf to /lustre1/project/stg_00056/octopus/cellranger/kalbus/tmp/tmp83t_0dkk
> [2021-04-30 18:19:48,396]    INFO Splitting genome tmp/genome.fa into cDNA at /lustre1/project/stg_00056/octopus/cellranger/kalbus/tmp/tmp26no_fj4
> [2021-04-30 18:19:48,397] WARNING The following chromosomes were found in the FASTA but does not have any "transcript" features in the GTF: JH584301.1, GL456382.1, CM000994.3, CM001003.3, CM001001.3, CM000997.3, MU069435.1, GL456378.1, JH584302.1, CM001006.3, CM001010.3, GL456211.1, GL456389.1, MU069434.1, GL456210.1, GL456367.1, GL456359.1, GL456387.1, GL456354.1, CM001011.3, GL456394.1, CM000999.3, GL456383.1, JH584303.1, CM001014.3, CM000995.3, GL456233.2, JH584300.1, GL456390.1, JH584296.1, CM001008.3, GL456392.1, CM000998.3, CM001005.3, JH584297.1, JH584304.1, GL456366.1, JH584299.1, CM001000.3, CM001004.3, CM001002.3, CM001009.3, GL456219.1, GL456396.1, GL456381.1, JH584295.1, GL456370.1, GL456221.1, CM001012.3, CM001013.3, GL456212.1, CM001007.3, GL456379.1, GL456385.1, CM000996.3, GL456372.1, GL456360.1, GL456368.1, JH584298.1, GL456239.1. No sequences will be generated for these chromosomes.
> [2021-04-30 18:19:48,399]   ERROR An exception occurred
> Traceback (most recent call last):
>   File "/data/leuven/329/vsc32990/miniconda3/envs/velocity/lib/python3.9/site-packages/kb_python/main.py", line 876, in main
>     COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
>   File "/data/leuven/329/vsc32990/miniconda3/envs/velocity/lib/python3.9/site-packages/kb_python/main.py", line 126, in parse_ref
>     ref_lamanno(
>   File "/data/leuven/329/vsc32990/miniconda3/envs/velocity/lib/python3.9/site-packages/kb_python/ref.py", line 591, in ref_lamanno
>     cdna_fasta_path = generate_cdna_fasta(
>   File "/data/leuven/329/vsc32990/miniconda3/envs/velocity/lib/python3.9/site-packages/kb_python/fasta.py", line 335, in generate_cdna_fasta
>     transcript_id = gtf_entry['group']['transcript_id']
> KeyError: 'transcript_id'
> 

**This was the command used:**

> 
> conda activate velocity
> 
> cd $PBS_O_WORKDIR
> 
> kb ref -i index.idx -g t2g.txt -f1 cdna.fa -f2 intron.fa -c1 cdna_t2c.txt -c2 intron_t2c.txt --workflow lamanno -n 4 \
> genome.fa.gz \
> genes.gtf.gz

Input files originate from here: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/635/GCA_000001635.9_GRCm39/

I tried this first on my own gtf for a non-model species and then I tried it on a standard mouse gtf because i thought the formatting of my gtf was the problem - but this seems not to be the case?
Could you give some more information on how the gtf should be formatted?

Thanks so much!
Ruth

**Comment by Lioscro** [comment]
It's due to the GTF entries that have an empty `gene_id` attribute. For instance, the very first GTF entry contains
```
gene_id ""; transcript_id "unknown_transcript_1"; anticodon "(pos:33..35)"; gbkey "tRNA"; note "annotated according to Bibb M.J., et. al. (1985) Cell 26:167-180"; product "tRNA-Phe"; exon_number "1";
```

The KeyError is coming from the fact that we assume every `exon` feature has a corresponding `gene_id` attribute (but this GTF contains exons without an appropriate `gene_id`). 

I also notice a lot of transcripts are assigned a `transcript_id "unknown_transcript_1"`, which seems to be a common occurrence of genome assemblies. Because `kb` splits the genome FASTA by unique `transcript_id`'s, these will also probably cause either an error or incorrect cDNA sequences.

**Comment by Lioscro** [comment]
Hi, @Ruth-hals, we've made a major refactor in our GTF and FASTA parsing code in the `devel` branch, which should hopefully help you out with more detailed error messages. However, entries without a correct `gene_id` attribute are ignored, so you may have to remove or change some entries in the GTF.

You can try it out by installing the `devel` branch with the following command.
```
pip install git+https://github.com/pachterlab/kb_python@devel
```
