### ISSUE TITLE
kb for multi-modal data

### ISSUE THREAD

**Issue by andrewjkwok** [pachterlab/kb_python#123]
Hi,

I am interested in doing some RNA velocity analysis on my single cell data, and i came across this awesome suite of tools to generate the spliced and unspliced counts to allow me to do this.

However, the data I have are from multi-modal profiling with both cell surface protein and RNA, and the reads of both layers of data are in the same fastq file. Looking at the tutorial for KITE workflow (https://www.kallistobus.tools/tutorials/kb_kite/python/kb_kite/) for feature-barcoding / multi-modal data, it's implemented for a fastq file containing only the antibody reads and generates a separate kallisto index for these reads. 

Is it possible to generate a single kallisto index for RNA and protein/antibodies so that I can get counts for both layers of data at the same time as there is only a single pair of fastq files?

Many thanks in advance.

**Comment by sbooeshaghi** [comment]
Hi @andrewjkwok,

This is a great question. Which assay have you generated data with and what is the read structure for the barcodes/cdna/surface protein barcodes?

**Comment by andrewjkwok** [comment]
The data was generated on the BD Rhapsody platform (whole transcriptome + BD Abseq) and sequenced @ 150bp, paired end (although basically only read 2 contains cDNA information).

The read structure is like this: https://teichlab.github.io/scg_lib_structs/methods_html/BD_Rhapsody.html, where the first read starts with a 52bp cell barcode (3x9 base barcodes with 2 linker regions, the first one 12 bases in length then the second 13 bases for a total of 27 + 25 = 52), followed by an 8 base UMI. The second read is where the RNA / surface protein cDNA data is.

The default BD pipeline for mapping uses STAR and just asks me to supply a genome reference and the ADT/Abseq reference and then spits out a concatenated matrix of both RNA and protein features, and I'm not sure if something similar could be reproduced with kallisto/bustools.

**Comment by andrewjkwok** [comment]
Yes - I've been posting in that issue to about the BDWTA option because I can't run kb count, but I'll leave that issue there. Thanks for considering the transcriptome + surface protein cDNA issue - will follow on your github and please let me know when there are updates.
