### ISSUE TITLE
Error when trying to install kb-python in Singularity container

### ISSUE THREAD

**Issue by angelolimeta** [pachterlab/kb_python#128]
**Describe the issue**
Hi! I'm trying to install kb-python and related analysis files (e.g. human genome ref sequence) into one big singularity container, as the compute environment I'm working in does not have internet access. I am trying to install the version that's available through conda (v0.26.0), but I can't seem to solve the environment.
Do you have any tips/help for running kb in a singularity environment? Or any other way that does not require internet access.
Any help would be greatly appreciated! 👍 

**What is the exact command that was run?**

I tried building it using the sylabs remote builder (https://cloud.sylabs.io/builder/) with the following recipe:
```
BootStrap: library
From: centos:7
%runscript
conda activate scRNAseq
kb ref --help

%post
yum clean all
yum -y update
yum -y install wget python3-devel.x86_64
cd /tmp
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash ./Miniconda3-latest-Linux-x86_64.sh -b -p /miniconda
/miniconda/bin/conda update -y conda
/miniconda/bin/conda create --name scRNAseq
source /miniconda/bin/activate
conda init
conda activate scRNAseq
conda install -c bioconda kb-python
conda deactivate
```

**Command output (with `--verbose` flag)**
The recipe failed to build due to the conda environment not being able to be solved.
The entire log is available here: https://pastebin.com/np9cciSD

**Comment by Lioscro** [comment]
Hi, @angelolimeta,

Does your python environment have access to `pip` by any chance? Most conda distributions come with `pip`, I believe.

Unfortunately, we don't directly maintain the `kb-python` installation through `bioconda`, so you may have to post an issue on the bioconda repo here: https://github.com/bioconda/bioconda-recipes

**Comment by angelolimeta** [comment]
Hi @Lioscro! Thanks for the swift reply! I managed to install it into a singularity container and run it using pip. I can also add that the installation through bioconda works fine on my local computer, i just couldn't manage to get it running in a singularity container.
Thanks a lot for the help! 👍
