### ISSUE TITLE
Scanpy dependencies?

### ISSUE THREAD

**Issue by kaji331** [pachterlab/kb_python#131]
When I installed kb-python 0.26.2 by pip3, scanpy and many dependencies were all installed by pip. I just want to make a singularity image containing only kb-python for ref/count, because I used to work with Seurat. Can the scanpy removed for kb-python dependencies? Thank you!

**Comment by Lioscro** [comment]
Hi, @kaji331, scanpy is used in report generation, which is a feature that we support. Therefore, we can not remove it from the requirements. If you really wish to remove the scanpy installed with kb, you can install kb first and simply remove scanpy with `pip uninstall scanpy`. Note that there will be errors if you are using `--report` to generate reports.

**Comment by kaji331** [comment]
T_T! Thank you very much for your explaination
