### ISSUE TITLE
Processing 10x data with alignment from paired reads

### ISSUE THREAD

**Issue by gouinK** [pachterlab/kb_python#135]
Hi all, thank you for this very convenient tool. I perform 2x150bp reads on my 10x Chromium libraries and generally when I run Cellranger I allow it to align using data from both reads. How would I go about doing the same with Kallisto, and specifically with this package? 

Thanks!

**Comment by Lioscro** [comment]
Hi, @gouinK,
Are you saying that your read 1 contains part of the cDNA sequence that is read through, from the barcode and UMI sequences? (i.e. your read 1 looks like this: `cell barcode-UMI-cDNA`)

**Comment by gouinK** [comment]
Hi, yes that is correct, thank you

**Comment by Lioscro** [comment]
Hi, @gouinK,
Sorry for the delayed response.
I don't think there is an easy way to do this currently. @sbooeshaghi any thoughts?

**Comment by sbooeshaghi** [comment]
Currently the way to do this would be to modify the code to append the read 1 bases after the barcode + umi to the biological read 2. Though in my experience I've not seen this done as read 1 is usually only sequenced for length(barcode) + length(UMI) cycles, 28bp for 10xv3. @gouinK can you show us an example dataset where read 1 is sequenced for 150bp?
