### ISSUE TITLE
BUTTERFLY: Bustools implementation

### ISSUE THREAD

**Issue by Nusob888** [pachterlab/kb_python#140]
Thank you for the great wrapper. 
Can I clarify whether the butterfly UMI correction (10.1186/s13059-021-02386-z) is implemented in bustools within kb_python?

The method looks great and I am looking to benchmark it for use on datasets. It looks like on the bustools git, the collapse function has been committed in April. 

If we have installed kb_python in June, can we assume this was integrated into the installation? and is therefore actively applied when we call --filter bustools?

Many thanks in advance for any clarification on this

**Comment by Lioscro** [comment]
Hi, @Nusob888,
the butterfly implementations have just been included in the latest bustools release, which was released 10 days ago.
We are still in the process of incorporating the new changes into `kb`, so for the time being you will have to use bustools directly if you would like those new functionalities.
