### ISSUE TITLE
How to manually change the threshold of UMI filtering in Kb count wrapper

### ISSUE THREAD

**Issue by yuzhong1997** [pachterlab/kb_python#142]
Hi, 

I'm just wondering if there are any options to change the threshold of cell filtering within the kb count wrapper.
As far as I know, there is one parameter to pass in order to do cell barcode filtering, i.e., --filter bustools.
Actually, I see "bustools whitelist --threshold" referencing the manual, which can do this. But, it seems like no integer parameter can be passed into the kb wrapper. Thanks.

Yu

**Comment by Lioscro** [comment]
Hi, @yuzhong1997,
An option to set the threshold will be included in the next release.

**Comment by yuzhong1997** [comment]
Hi, @Lioscro 

Thanks. Looking forward to it~

Yu
