### ISSUE TITLE
NaN value for Ensembl gene_id without gene names

### ISSUE THREAD

**Issue by vjorgensen** [pachterlab/kb_python#144]
**Ensembl genes without gene names give a NaN or U1 output for adata.var**
I follow the kb tutorial for getting started and download all necessary files from Ensembl. Then, when I try to map the Ensembl "gene_id" to the "gene_name",  gene_ids WITHOUT a gene name appear as NaN or U1. Essentially what is happening is that in the t2g file (I believe), a column is getting shifted such that it takes some value U1 or NaN when no gene name is provided for a given gene_id.

This happens for ~20,000 genes which is pretty significant. It also causes issues with downstream analysis and adata.var not being unique. I suggest that when a gene name is not provided, the ensemble gene_id could be used in it's place.

<img width="1105" alt="Screen Shot 2021-08-09 at 11 02 40 AM" src="https://user-images.githubusercontent.com/56095263/128752439-745c8dd6-f44c-4bbe-af2c-5471e0eb4c63.png">

<img width="577" alt="Screen Shot 2021-08-09 at 11 03 01 AM" src="https://user-images.githubusercontent.com/56095263/128752484-0f8db451-47a3-4001-bada-d34500b680fb.png">

<img width="561" alt="Screen Shot 2021-08-09 at 11 04 07 AM" src="https://user-images.githubusercontent.com/56095263/128752600-7c1049b0-4ff1-4faa-961a-db4cd58522a4.png">

**What is the exact command that was run?**
```
adata.var["gene_id"] = adata.var.index.values

t2g = pd.read_csv("output_batch/transcripts_to_genes.txt", header=None, names=["tid","gene_id","gene_name"], sep="\t", usecols=[0,1,2])
t2g.index = t2g.gene_id
t2g = t2g.loc[~t2g.index.duplicated(keep='first')]

adata.var["gene_name"] = adata.var.gene_id.map(t2g["gene_name"])
adata.var.index = adata.var["gene_name"]
```

**Command output (with `--verbose` flag)**
```
Please copy and paste *VERBOSE* output here.
```

**Comment by Lioscro** [comment]
Hi, @vjorgensen,
I'm not sure I'm understanding the issue fully. Are you saying that the genes annotated as `U1` are incorrect?
A quick search for each of the gene IDs in the `gene_id` column of the `adata.var.loc[adata.var['gene_name'] == "U1"] tells me that these genes do indeed have a gene name of `U1` (for instance, http://useast.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000275405;r=KI270713.1:21861-22024;t=ENST00000619109).

When there is no corresponding `gene_name` for a particular `gene_id`, I don't think simply placing the gene ID in the `gene_name` column is appropriate here, as the `gene_id` and `gene_name` columns should only contain values that exist in the annotation GTF.

**Comment by vjorgensen** [comment]
I think Sina might have already fixed the issue! He told me to make a Github issue a while ago but I never got around to it. I think before it didn't give a "NaN" value, but something else. So now when I tried to go back and run the code, I pasted what I saw without remembering what exactly the error was. 

Anyways, problem solved thanks!
