### ISSUE TITLE
Request for Kb to include option to output Bam file

### ISSUE THREAD

**Issue by crystalizee** [pachterlab/kb_python#147]
Hi all!

I just wanted to request kb count to also have the pseudobam and genomebam option from kallisto quant command.

Thanks!

**Comment by Lioscro** [comment]
Hi, @crystalizee,
`kallisto quant` is not used in the pipeline. Could you clarify what you mean here?

**Comment by ricomnl** [comment]
This would be addressed by: https://github.com/pachterlab/kb_python/pull/184
