### ISSUE TITLE
Use kb/kallisto for 10X_Visium

### ISSUE THREAD

**Issue by tabdelaal** [pachterlab/kb_python#154]
Hi,

I was wondering whether or not kb (or kallisto) can be used to perform pseudo-alignment for the spatial transcriptomics data from 10X (Visium data), assuming it's the same technology as 10xv3?!

Thank you

**Comment by Yenaled** [comment]
Yes, and, in fact, the devel/beta version of kallisto - https://github.com/pachterlab/kallisto/tree/devel - includes a -x Visium option. It's exactly like doing -x 10XV3. The devel version of kallisto will be officially released soon.

**Comment by Yenaled** [comment]
If you run the default `kb count -x 10XV3`, it won't work because it'll use the 10XV3 (not visium) barcode list. Use `-w None` when running kb (so the 10XV3 barcode list doesn't get used), or simply run kallisto and bustools by themselves.

**Comment by tabdelaal** [comment]
Thanks a lot. Yes, that's the problem indeed.

I was not using ```-w``` with the 10xv3 as technology. I did input my own barcodes and it's working fine now. 

One last question, if I use ```-w None```, does this means that kallisto will look up all the barcodes in read 1 and ignore the whitelist of the technology chosen?

**Comment by Yenaled** [comment]
That is correct; with -w None, the "bustools whitelist" command will be run and will algorithmically try to figure out a whitelist based on the observed barcodes in your reads. This is useful in situations where you don't actually have a whitelist of barcodes already (like in Drop-seq).

**Comment by tabdelaal** [comment]
Thank you, that's very clear now.
