### ISSUE TITLE
My output adata does not make sence

### ISSUE THREAD

**Issue by saramoein372** [pachterlab/kb_python#155]
Hello pachter lab,

Thank you for sharing your code. I am running my asap-seq data  with kaliisto|KB.
But my results looks something I am missing in run. Because my generated adata file is:

adata
AnnData object with n_obs × n_vars = 61 × 5
    var: 'feature_name'
>>> adata.obs.head()
Empty DataFrame
Columns: []
Index: [AACCAACAGATGTTCC, AACCAACCAAAGGCCA, AACCAACCACGATTAC, AACCAACCATAGCCAT, AACCAACTCGCAGATT]

I am not sure my barcodes are working like index, while they should be as the "barcode" column, as you explained in your tutorial.

Would you please let me know your thoughts and comments? I really appreciate your support, since this is some days that I am trapped and can not find the problem.

Thanks,
Sara

**Comment by Lioscro** [comment]
Hi, @saramoein372,
Not sure if I understand what you are referring to. Is your concern that the column is not named `barcode`?

**Comment by saramoein372** [comment]
Hi Joseph,

Thanks. I think I found the problem. When changing the version of my
python, it solved the problem.
