### ISSUE TITLE
`--gene-names` results in an anndata object where the vars are ENSEMBL IDs

### ISSUE THREAD

**Issue by Lioscro** [pachterlab/kb_python#160]
> @Lioscro to your point, running the following command (using --gene-names)
> kb count --h5ad -i ~/utilities/kb/index.idx -g ~/utilities/kb/t2g.txt -x 10XV3 -o "${cDNA_seq[i]}_kb_output" --tmp "${cDNA_seq[i]}_tmp" --workflow lamanno -c1 ~/utilities/kb/spliced_t2c.txt -c2 ~/utilities/kb/unspliced_t2c.txt --filter bustools --gene-names -t 40 ${cDNA_seq1[i]} ${cDNA_seq2[i]}
> 
> still results in an anndata object where the vars are ENSEMBL IDs

https://github.com/aristoteleo/dynamo-release/issues/285#issuecomment-1052714189
@jmartinrufino What version are you using?

**Comment by jmartinrufino** [comment]
kb_python 0.27.0

**Comment by Lioscro** [comment]
Are both your unfiltered matrix (`counts_unfiltered/adata.h5ad`) and your filtered matrix (`counts_filtered/adata.h5ad`) not respecting the `--gene-names` setting?

**Comment by Gavin-Lijy** [comment]
Me too
