### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by FionaMoon** [pachterlab/kb_python#166]
Hi,
I got trouble when I try to install `kb_python`.
I can't install it either by pip or by conda.
It seems that the porblem is caused by `pysam`.
```
      collect2: error: ld returned 1 exit status
      error: command '/xtdisk/fangxd_group/liangyue/miniconda/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pysam

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

Thank you inadvance!

Fiona

**Comment by Lioscro** [comment]
Hi, @FionaMoon,

A few questions for you first.
What Python version, OS, and CPU architecture are you using?
Seems like something is misconfigured such that pysam can not be compiled (probably due to samtools compilation).

What is the output if you try to install pysam directly?
```
pip install pysam
```
or
```
conda install pysam
```

**Comment by FionaMoon** [comment]
Hi,
Thank you for you reply!

I have python 3.8.13 & 3.9.10 environments.
My operating system is GNU/Linux 
CPU Architecture: x86_64

When I try to install pysam directly by `pip install pysam`:

``` note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pysam

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by Lioscro** [comment]
This seems like an issue on `pysam`'s side. I'm not very knowledgeable on their internals, I would recommend submitting an issue on their Github (https://github.com/pysam-developers/pysam).

**Comment by FionaMoon** [comment]
Thank you for your reply !
I'll ask pysam side .



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Joseph ***@***.***> |
| Date | 06/06/2022 21:24 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [pachterlab/kb_python] Installation Error (Issue #166) |

This seems like an issue on pysam's side. I'm not very knowledgeable on their internals, I would recommend submitting an issue on their Github (https://github.com/pysam-developers/pysam).

**Comment by FionaMoon** [comment]
Hi All，
I've solved this question by install the newest version of conda.
