### ISSUE TITLE
kb_python.config.UnsupportedOSError

### ISSUE THREAD

**Issue by FionaMoon** [pachterlab/kb_python#169]
Hi developer,
After installation of kb_python [#166](https://github.com/pachterlab/kb_python/issues/166),
I met another problem when run the code from tutorial.
```
kb ref -i index.idx -g t2g.txt -f1 cdna.fa -f2 intron.fa -c1 cdna_t2c.txt -c2 intron_t2c.txt --workflow lamanno -n 8 \
> Mus_musculus.GRCm38.dna.primary_assembly.fa.gz \
> Mus_musculus.GRCm38.98.gtf.gz

Traceback (most recent call last):
  File "/xtdisk/miniconda/envs/scDIOR/bin/kb", line 8, in <module>
    sys.exit(main())
  File "/xtdisk/miniconda/envs/scDIOR/lib/python3.8/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/xtdisk/miniconda/envs/scDIOR/lib/python3.8/site-packages/kb_python/main.py", line 1266, in main
    raise UnsupportedOSError(
kb_python.config.UnsupportedOSError: Failed to find compatible kallisto binary. Provide a compatible binary with the `--kallisto` option or run `kb compile`.
```
I re-install kallisto by `conda install -c bioconda kallisto`, but this seems don't work.
So where can I find compatible kallisto binary? 
Thank you inadvance!

**Comment by Yenaled** [comment]
Which binary you download depends on what OS you're using (see the kallisto GitHub page for binaries you can download). Nonetheless, your best option might be to compile kallisto from source.
