### ISSUE TITLE
command not found after pip3 installation

### ISSUE THREAD

**Issue by tsofiya** [pachterlab/kb_python#185]
Hi,
I'm trying to install kallisto-bus using pip3 command:
pip3 install kb-python
After installation is finished (no errors shows), I tried using the tool using kb command, but it just writes: 
kb: command not found
Am I missing something?
Thanks!

**Comment by Lioscro** [comment]
It's probably due to how your python installation and/or paths are set up. Simplest way to get around the binary would be
```
python3 -c 'from kb_python.main import main; main()'
```
