### ISSUE TITLE
Analysis report /metrics / QC for smart-seq3

### ISSUE THREAD

**Issue by royfrancis** [pachterlab/kb_python#191]
I get few counts at the end of my pipeline and would like to know why. I am interested in FastqQC report (read quality), mapping qc (alignment, mapping rates etc) and/or multiqc reports. Is there any way to get any metrics on what is happening in the pipeline?

When I run smart-seq3 with `--report`, I get this

`kb: error: Argument 'report' is not supported for technology 'SMARTSEQ3'.`

What's covered in this report if it did work?

Another question is if it's possible to get BAM files, so I can run my own mapping QC?

```
kb_python 0.27.3
kallisto, version 0.48.0
bustools, version 0.42.0
```

**Comment by Yenaled** [comment]
Hi! The QC usually shows things like the knee plot and some other things stored in the JSON info files (e.g. number of reads mapped, number of records in the BUS file, UMI information, etc.). You can get that information by manually inspecting the JSON files in the output directory (or by looking at the output when running kb with the --verbose option specified).

No information about quality scores (or other details in FASTQ files) are available.

If you're interested in the quality of the sequencing reads themselves, I recommend fastQC (or a similar tool).

The devel branch of kb-python (which will be merged into the next stable release soon but you can install it right now) supports a --genomebam option for generating BAM files.
