### ISSUE TITLE
Can kb_python work with SMARTSeq v4  stranded library kit?

### ISSUE THREAD

**Issue by yeroslaviz** [pachterlab/kb_python#194]
I have data set done with the SMARTSeq Stranded Library Kit. The data is paired-end.
It uses no barcodes and no UMIs.

In the manual they state 

```
It generates RNA-seq data that are at par with the industry-leading SMART-Seq v4 Ultra® Low Input RNA Kit 
for Sequencing without the additional requirement for Nextera® library preparation.
```

I am not sure what to put in the parameter `-x`. Can I use `SMARTSEQ2` as it also have no umi or barcodes and seems to include all the read in the quantification?

thanks

Assa

**Comment by Yenaled** [comment]
Yes, use -x smartseq2 (the read structure of smartseqv4 is identical to that of smartseq2).

**Comment by yeroslaviz** [comment]
sorry, I forgot to answer. I have ran it with the smart2seq parameters. If I have ERCC spike_ins in the samples, is it possible to add the ERCC sequences to the transcriptome and gtf file and run it like with the genome in STAR/HiSat2?

thanks

**Comment by Yenaled** [comment]
Yes, you can add the spike in sequences into the FASTA and edit the GTF accordingly, and recreate the index. The spike ins will then be quantified when you run kb count.

**Comment by yeroslaviz** [comment]
thanks.
