### ISSUE TITLE
kb ref prebuilt indices

### ISSUE THREAD

**Issue by ryanz8** [pachterlab/kb_python#197]
Hi, `kb ref` provides prebuilt indices with the `-d` flag:

```
  -d {human,mouse,linnarsson}
                        Download a pre-built kallisto index (along with all
                        necessary files) instead of building it locally
```

However, I haven't been able to find anywhere a description of these indices or how they were built.

I would appreciate any information or documentation that sheds some light on this.
Thanks!

**Comment by Yenaled** [comment]
Don't use the prebuilt indices -- they haven't been updated in a while and are outdated. I strongly recommend generating your own index.

You can view the cDNA FASTA and transcripts-to-gene map for the prebuilt index; if you want to reproduce generating it, I'm afraid it was generated by an older version of kb-python (hence outdated). Just generate your own index . We'll update+document the prebuilt indices once our next version of kallisto is out (this summer).

**Comment by ryanz8** [comment]
Understood, thanks for the response!
