### ISSUE TITLE
kb-python for isoform level analysis on bulk RNAseq

### ISSUE THREAD

**Issue by harshini-c** [pachterlab/kb_python#200]
Hello, 

I was wondering if we can use your tool to perform isoform level analysis on bulk nuclear RNAseq data? 
Do you think the counts obtained would be accurate for downstream differential expression analyses? 

Would be great to know your thoughts in this regard,

Thank you

**Comment by Yenaled** [comment]
I wouldn't recommend it. For one, most stuff in the nucleus is unspliced RNAs (therefore resolving isoforms may not be possible). Secondly, if your data doesn't have UMIs, there might not be a good way to normalize for transcript length.

You can try and it would be a very interesting research question to explore, but I can't say definitively that there's a good, established workflow for isoform-level bulk nucleus data quantification.

**Comment by harshini-c** [comment]
thank you for the quick reply and your insights.  Appreciate it.
