### ISSUE TITLE
Exon Quantification

### ISSUE THREAD

**Issue by shashkat** [pachterlab/kb_python#201]
Hi there, firstly thanks for making such an awesome tool. I have had great results with the transcript quantification of single cell data. 
However, now I want to move into exon level quantification as that is the next step in my analysis. Could you please guide how I can try to do that. As far as I know, kallisto currently doesn't have that feature, but getting insights into how to approach it would be of great help. Any help is appreciated!

Thank You!

**Comment by Yenaled** [comment]
Hmm, for transcripts, we go into the GTF, extract the exons and stitch them together. I guess for exons, the approach would be to simply index the exons individually. Everything else should proceed as normal.

**Comment by shashkat** [comment]
Okay, thanks a lot for your quick response! I will give it a try and see if it works.

Regards,

**Comment by shashkat** [comment]
Hi there, so i have been able to implement it successfully by making some modifications in the gtf and obtaining a new index file. However, I was wondering about a basic issue regarding the mapping of reads in kallisto. Could you please be kind enough to explain it?

In the following case, how does the tool approach to map the read to the appropriate exon?

<img width="828" alt="Screenshot 2023-04-11 at 11 07 46 PM" src="https://user-images.githubusercontent.com/72993520/231245390-86fd697e-1b46-4d9b-9dfe-306a78eb4f9e.png">

**Comment by Yenaled** [comment]
That read will multimap -- both exons will be mapped.

What you do with the multimapping depends on how you run "bustools count". You can choose to either discard the multimapping (default), assign 0.5 to both exons, do probablistic assignment (e.g. an EM algorithm), etc.

**Comment by Yenaled** [comment]
That should be fine but it's hard to say what exactly you're doing with the GTF. The best thing to do would be to run kb ref and inspect the FASTA file produced by it (the output file of -f1) and see if it's giving you the target sequences (exons in this case) that you want to quantify.
