### ISSUE TITLE
Tutorial question on expected_num_cells

### ISSUE THREAD

**Issue by anniliu7** [pachterlab/kb_python#211]
**Describe the issue**
Hi. I wondered if anyone knows what the variable "expected_num_cells" refers to, when filtering the empty drop in the kb-python tutorial (https://www.kallistobus.tools/tutorials/kb_getting_started/python/kb_intro_2_python/)? Thank you so much for your help in advance!

**What is the exact command that was run?**
```
# These are the Python codes.
# Filter the cells according to the threshold determined from the knee plot
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_cells(adata, min_counts=knee[expected_num_cells])
```

**Command output (with `--verbose` flag)**
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[48], line 1
----> 1 sc.pp.filter_cells(adata, min_counts=knee[expected_num_cells])

NameError: name 'expected_num_cells' is not defined
```

**Comment by Yenaled** [comment]
It's the number of barcodes you think you should keep based on the knee plot, or it's the number of barcodes that's described in the publication (which you can verify is reasonable by, again, inspecting the knee plot).

**Comment by anniliu7** [comment]
> It's the number of barcodes you think you should keep based on the knee plot, or it's the number of barcodes that's described in the publication (which you can verify is reasonable by, again, inspecting the knee plot).

Got it. Thank you for your explanation.
