### ISSUE TITLE
the kb automatically terminate

### ISSUE THREAD

**Issue by doudou159** [pachterlab/kb_python#214]
**Describe the issue**
A clear and concise description of what the issue is.
Hello，If the server automatically terminates the process due to insufficient memory, can the kb count continue to calculate after the terminated process? Or  need to start the calculation from the beginning with a new submission of a new task？thank you .

**What is the exact command that was run?**
```
kb count ...
```

**Command output (with `--verbose` flag)**
```
Please copy and paste *VERBOSE* output here.
```

**Comment by Yenaled** [comment]
Sorry for late reply -- kb count will need to be run anew. The bulk of kb count lies in the read mapping step and it's impossible to resume read mapping from the middle of a FASTQ file.
