### ISSUE TITLE
fixed RNA profiling

### ISSUE THREAD

**Issue by yfarjoun** [pachterlab/kb_python#215]
**Describe the issue**
Fixed RNA profiling is a relatively new assay provided by the Chromium system . CellRanger also provides a [pipeline](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/multi-frp) for analyzing the resulting data.  

I was wondering if the kb team has any best-practices or suggestions for how to run KB on fixed RNA profiling data.

Left to my own devices, I was considering creating a reference from the probes in the probe-set and then running as normal, but I'm not sure if that's the correct approach.

**Comment by Yenaled** [comment]
I think this can use the following workflow described here:

https://www.biorxiv.org/content/biorxiv/early/2022/10/10/2022.10.09.511501.full.pdf
