### ISSUE TITLE
Support for Demultiplexed Smart-seq3 data

### ISSUE THREAD

**Issue by kvn95ss** [pachterlab/kb_python#217]
I'm aware there is already an issue submitted to github, [this one ](https://github.com/pachterlab/kb_python/issues/216#issue-1862029795) to be exact. The user has single end data and the barcodes, in my case the samples are also single end, but they have already been demultiplexed and I don't have access to the BCL files (Sequencing performed at external center, so can't have access to that).

Since the samples have been demultiplexed, the barcodes are already present in the read headers. I also have them in a separate list, is there any way I can use Kallisto-bustools for my data?

**Comment by Yenaled** [comment]
How do your reads look? Is each "cell" in its own separate FASTQ file? If so, then you can still use kallisto. There is a "batch" option in kallisto bus where you can list each file as follows:

`cell1 cell1_r1.fastq;gz cell1_r2.fastq.gz
cell2 cell2_r1.fastq;gz cell2_r2.fastq.gz
cell3 cell3_r1.fastq;gz cell3_r2.fastq.gz`

**Comment by kvn95ss** [comment]
We have used smart-seq3 to capture extracellular RNA from spent media, so as such each "cell" in our case is representation of the (few) collective cells from same culture.

Would the batch option still be appropriate for our analysis?
