### ISSUE TITLE
kallisto index file not found index.idx_cdna

### ISSUE THREAD

**Issue by feasiblee** [pachterlab/kb_python#219]
Here, I found a question, please ask everyone, is Error: kallisto index file not found index.idx_cdna.
Detailed description:
kb count --h5ad -i index.idx_cdna,index.idx_intron.0,index.idx_intron.1,index.idx_intron.2,index.idx_intron.3,index.idx_intron.4,index.idx_intron.5,index.idx_intron.6,index.idx_intron.7 -g t2g.txt -x 10xv2 -o SRR6470907 -c1 spliced_t2c.txt -c2 unspliced_t2c.txt --workflow lamanno --filter bustools -t 2 \
> SRR18516664_1.fastq.gz \
> SRR18516664_2.fastq.gz 
[2023-10-13 01:02:00,174]    INFO Generating BUS file using 9 indices
[2023-10-13 01:02:00,175]    INFO Using index index.idx_cdna to generate BUS file to SRR6470907/tmp/bus_part0 from
[2023-10-13 01:02:00,175]    INFO         SRR18516664_1.fastq.gz
[2023-10-13 01:02:00,175]    INFO         SRR18516664_2.fastq.gz
[2023-10-13 01:02:00,183]   ERROR kallisto 0.46.2
Generates BUS files for single-cell sequencing

Usage: kallisto bus [arguments] FASTQ-files

Required arguments:
-i, --index=STRING            Filename for the kallisto index to be used for
pseudoalignment
-o, --output-dir=STRING       Directory to write output to
-x, --technology=STRING       Single-cell technology used

Optional arguments:
-l, --list                    List all single-cell technologies supported
-t, --threads=INT             Number of threads to use (default: 1)
-b, --bam                     Input file is a BAM file
-n, --num                     Output number of read in flag column (incompatible with --bam)
-k, --kmer                    Alignment is done per kmer
--verbose                 Print out progress information every 1M proccessed reads

Error: kallisto index file not found index.idx_cdna

**Comment by Yenaled** [comment]
You should: 1) Upgrade to the latest version kb-python via pip install, 2) Run kb ref to create your new index, 3) Run kb count using that index

The "multiple indices" feature that you're using is something that we no longer support.

**Comment by feasiblee** [comment]
Thank you very much for your answer, thank you

> You should: 1) Upgrade to the latest version kb-python via pip install, 2) Run kb ref to create your new index, 3) Run kb count using that index
> 
> The "multiple indices" feature that you're using is something that we no longer support.
