### ISSUE TITLE
If it doesn't exist yet, is it possible to add an option that filters the genes by abundance

### ISSUE THREAD

**Issue by NikTuzov** [pachterlab/kb_python#220]
Hello:

Presently, we can limit the barcodes to the most frequent ones by using the following arguments:

--filter bustools --filter-threshold threshold_value

Is there a similar option to restrict the list of genes/features to the most expressed ones, e.g. by using the total count of barcodes per gene, or by keeping the k% of genes with the highest total count. If not, could it be added to kb count?

Regards,
Nik Tuzov

**Comment by Yenaled** [comment]
The reason we're not really adding such options to kb count is that we believe that all filtering operations should be done downstream. kb-python is designed to generate raw count matrices that can be read into downstream tools and/or to form an anndata object. I personally always do my work on unfiltered count matrices and then filter downstream.

**Comment by NikTuzov** [comment]
Thank you very much for a prompt reply.

**Comment by NikTuzov** [comment]
Closed.
