### ISSUE TITLE
kb count settings/config for the new 10x Visium (11mm capture area) dataset 

### ISSUE THREAD

**Issue by gauravgadhvi** [pachterlab/kb_python#223]
Hi team KB,

We are trying to use **kb count** with a new **10x Visium** dataset (https://www.10xgenomics.com/resources/datasets/visium-cytassist-mouse-embryo-11-mm-capture-area-ffpe-2-standard) which has the same specs as the Visium technology supported by kb, but only has a larger capture area of 11mm instead of 6.5 mm. This shouldn't matter for running kb count on the dataset, although the output we get for the spliced/unspliced counts is quite strongly sparse and gets a pseudoalignment of 3% and 1.8% unique alignment. Is this something you've encountered before or is there a special setting we could use instead of the -x Visium flag for this kind of dataset? I believe the read configurations for the R1 and R2 in the new Visium are the same as the older version.

Here is the command I used to run **kb count** : 
```
kb count --h5ad --verbose 
-i ./GRCm38_mm10__kbIndex.idx 
-g ./GRCm38_mm10__t2g.txt 
-x Visium 
-w ./spaceranger-2.1.1/lib/python/cellranger/barcodes/visium-v5.txt 
-c1 ./GRCm38_mm10__cDNA_t2c.txt -c2 ./GRCm38_mm10__intron_t2c.txt 
--workflow lamanno 
-m 90G -t 8 
-o ./ 
./CytAssist_11mm_FFPE_Mouse_Embryo_S1_L004_R1_001.fastq.gz  ./CytAssist_11mm_FFPE_Mouse_Embryo_S1_L004_R2_001.fastq.gz
```

The reference genome and transcriptome I used for generating the kb-index are :
```
Mus_musculus.GRCm38.dna.primary_assembly.fa.gz
mm10.ncbiRefSeq.gtf
```

Any suggestions regarding the new 10x Visium dataset are highly appreciated. Thank you!

**Comment by Yenaled** [comment]
The dataset shouldn't be any different when running kb count -- no special setting is needed.

As for the low mapping rate, i'll download the dataset and check myself when i have the time to see what's going on (ping me if i forget).

**Comment by Yenaled** [comment]
OK @gauravgadhvi I think I figured out the issue. You need to use --strand=unstranded when running kb count.

**Comment by gauravgadhvi** [comment]
@Yenaled Thank you so much for trying it and sharing the setting. I was not sure if the paired-end libraries would be unstranded and didn't think about the option! I really appreciate your help!
