### ISSUE TITLE
Custom fasta and gtf file based on subset of genes for multiple species

### ISSUE THREAD

**Issue by gracedai23** [pachterlab/kb_python#231]
I am trying to construct a transcriptome index using kb ref for a metatranscriptomic analysis project, on a subset of genes of interest for a few species. I created my own fasta file and gtf file for kb ref as shown below. 

My fasta file looks something like this: 
>SM9_RS01950|Methanobrevibacter-millerae|SM9|hmd|1|517037|518035
TTATATTTTTTGAGGTTCCAATCCTAATTGTTTAATCACATCAGTCACATCTGCATAATTACCATAAGTTGGTG...
>SM9_RS01955|Methanobrevibacter-millerae|SM9|hmd|2|518159|519172
TTATTTGTCTTTACCTAAGTAATCTAATACGGTAGGAACGATTTCTGCTAATGAACCGAAGTTCA...

And the corresponding line in my gtf file to that first sequence looks like:
NZ_CP011266.1	RefSeq	gene	517037	518035	.	-	.	gene_id "SM9_RS01950"; transcript_id ""; db_xref "GeneID:26735371"; gbkey "Gene"; gene "hmdB"; gene_biotype "protein_coding"; locus_tag "SM9_RS01950"; old_locus_tag "sm9_0396"; 

The gtf files for the species of interest don't have transcript_id's, so I am using the gene_id as the unique identifier here, and it is the first part of each header in the fasta file. Should this work for creating the transcriptome index?

**Comment by Yenaled** [comment]
The headers of your FASTA files need to have > at the beginning.

If you just want to create a transcriptome index directly from a FASTA file, you don't need a GTF file. You need a GTF file only when you want to extract transcripts from genes (i.e. each gene has multiple transcripts).

**Comment by Yenaled** [comment]
Perhaps I misunderstood -- you might be using a GTF files to extract specific regions from your FASTA sequences (so you're not using those FASTA sequences directly). In that case, you'll need a GTF to extract those regions. Your GTF with just gene_ids should work (i.e. the entire gene will be considered a "transcript").

**Comment by gracedai23** [comment]
thanks for the quick response - apologies, my fasta headers do start with '>', it got omitted in the formatting above!
I am not using my gtf file for extractions, the sequences present in the fasta represent the exact sequences iIwant to use for the index. Do I still need to use kb ref then, or should I just directly go to the kallisto index and kallisto quant step (even though it is not a genome file and not a transcriptome file)? I assumed I couldn't do that because the kallisto manual says "The Fasta file supplied can be either in plaintext or gzipped format. Note: Do not supply the genome Fasta file; the Fasta file must be a transcriptome Fasta."
