### ISSUE TITLE
kb-python version 0.28.2 giving problems on m1 mac

### ISSUE THREAD

**Issue by shashkat** [pachterlab/kb_python#236]
**Describe the issue**
A clear and concise description of what the issue is.

When I installed kb-python using `pip install kb-python`, it does get installed but when i try to download mouse index using `kb ref -d mouse -i index.idx -g t2g.txt`, i get following error:

```
Traceback (most recent call last):
  File "/Users/shashankkatiyar/new_miniforge_mamba/envs/sc/bin/kb", line 8, in <module>
    sys.exit(main())
  File "/Users/shashankkatiyar/new_miniforge_mamba/envs/sc/lib/python3.8/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/Users/shashankkatiyar/new_miniforge_mamba/envs/sc/lib/python3.8/site-packages/kb_python/main.py", line 1583, in main
    raise UnsupportedOSError(
kb_python.config.UnsupportedOSError: Failed to find compatible kallisto binary. Provide a compatible binary with the `--kallisto` option or run `kb compile`.
```

also, when i run `kb info` command, i get following error:

```
Traceback (most recent call last):
  File "/Users/shashankkatiyar/new_miniforge_mamba/envs/sc/bin/kb", line 8, in <module>
    sys.exit(main())
  File "/Users/shashankkatiyar/new_miniforge_mamba/envs/sc/lib/python3.8/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/Users/shashankkatiyar/new_miniforge_mamba/envs/sc/lib/python3.8/site-packages/kb_python/main.py", line 1528, in main
    display_info()
  File "/Users/shashankkatiyar/new_miniforge_mamba/envs/sc/lib/python3.8/site-packages/kb_python/main.py", line 81, in display_info
    info = f'kb_python {__version__}\n{get_binary_info()}'
  File "/Users/shashankkatiyar/new_miniforge_mamba/envs/sc/lib/python3.8/site-packages/kb_python/main.py", line 69, in get_binary_info
    kallisto_version = '.'.join(str(i) for i in get_kallisto_version())
TypeError: 'NoneType' object is not iterable
```

the version of kb-python that was installed using the `pip install kb-python` command is 0.28.2.

I have an M1 MacBook air, and when i tried to do the same thing on a cluster (running these commands on kb-python version 0.28.2), which has OS linux, it ran successfully. Also, when I installed an older version of kb-python (0.27.3), it ran successfully on my macbook. So probably something is wrong with the way the new version of kb-python operates on my OS/architecture.

Regards,
Shashank

**Comment by Yenaled** [comment]
OK yeah, the kallisto binary is not working on your M1 Mac. Type kb count (without any options), and, in the menu, it will show you where the kallisto binary is located. Try running that binary (just type in the path and hit enter), and see what error message pops up.

OS support has become an issue with the newly packaged kallisto binaries (because kallisto was updated to version 0.50.1 which was a necessary update to process introns in the transcriptome index much more space-efficiently and time-efficiently).

**Comment by shashkat** [comment]
The output upon just running the kallisto binary's path was:

```
dyld[49519]: Library not loaded: /usr/local/opt/hdf5/lib/libhdf5.310.dylib
  Referenced from: <0D845FF0-6535-30AA-B573-4EA77382A171> /Users/shashankkatiyar/new_miniforge_mamba/envs/sc/lib/python3.8/site-packages/kb_python/bins/darwin/kallisto/kallisto
  Reason: tried: '/usr/local/opt/hdf5/lib/libhdf5.310.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/hdf5/lib/libhdf5.310.dylib' (no such file), '/usr/local/opt/hdf5/lib/libhdf5.310.dylib' (no such file), '/usr/local/lib/libhdf5.310.dylib' (no such file), '/usr/lib/libhdf5.310.dylib' (no such file, not in dyld cache)
zsh: abort
```

Thanks a lot for your help!

**Comment by Yenaled** [comment]
Hmm, interesting, it's not detecting your binary. If it detects your processor is ARM, it should have given you the following binary:

/Users/shashankkatiyar/new_miniforge_mamba/envs/sc/lib/python3.8/site-packages/kb_python/bins/darwin/m1/kallisto/kallisto

When you get the chance, can you open python and type in the following:

```
import platform

print(platform.system())
print(platform.processor())
print(platform.version())
print(platform.machine())
print(platform.architecture())
```

Then post the output -- and I'll try to figure out why M1 is not being detected.

In the meantime, when you run kallisto, you can specify:

`kb ref --kallisto=/Users/shashankkatiyar/new_miniforge_mamba/envs/sc/lib/python3.8/site-packages/kb_python/bins/darwin/m1/kallisto/kallisto
`

**Comment by shashkat** [comment]
Hey @Yenaled thank you so much for your reply!

Upon running those commands in python, I get the following:

```
>>> import platform
>>> print(platform.system())
Darwin
>>> print(platform.processor())
i386
>>> print(platform.version())
Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
>>> print(platform.machine())
x86_64
>>> print(platform.architecture())
('64bit', '')
```

Sure, I will use kb in that manner thanks!

**Comment by Yenaled** [comment]
Ah ok, I see, python thinks you’re using an intel processor (i386) so the intel-version of kallisto is being run which obviously won’t work on M1. I imagine it’s because of something in your environment (miniforge mamba) that’s causing python to think you’re using i386. I don’t know of a good solution other than either changing your environment or the using the recommendation I provided above.

**Comment by shashkat** [comment]
Hey @Yenaled! Sorry for my late response. You are right. For some reason, in my base conda env, the platform module detects my processor correctly, but that is not the case for all the other conda envs. I am currently trying to figure out why that is the case. But yes, as you suggested, in the base env, even with the latest version of kb-python, the commands work without explicit specification of the correct kallisto binary.

Thank you so much for all your help, it really means a lot!
