### ISSUE TITLE
Is kb-python capable of processing many samples in one command?

### ISSUE THREAD

**Issue by shashkat** [pachterlab/kb_python#237]
I want to process multiple single-cell sequencing fastq files using kb-python. In the kallisto documentation, it says the following:

"Important note: only supply one sample at a time to kallisto. The multiple FASTQ (pair) option is for users who have samples that span multiple FASTQ files. "

Since kb-python uses kallisto, I was confused if it also necessitates only one sample given to it at a time. Specifically, if I run the following command, will I get desired behaviour?

```
kb count -i ../../references/mouse/index.idx -g ../../references/mouse/t2g.txt -x 10xv2 -t 8 -o kallisto_output --h5ad \
fastqs/Brain_R1_001.fastq.gz \
fastqs/Brain_R2_001.fastq.gz \
fastqs/Spleen_R1_001.fastq.gz \
fastqs/Spleen_R2_001.fastq.gz
```

Also, I was curious that in case one has multiple fastqs for one sample (when one indeed is required to submit all the files in one command), are the files read in order such as:
read_1_file_1, read_1_file2, read_2_file_1, read_2_file_2 
or is it:
read_1_file_1, read_2_file_1, read_1_file2, read_2_file_2

Any help would be greatly appreciated!

Regards,
Shashank

**Comment by Yenaled** [comment]
You'll get the desired behavior in kb-python and the way you're running it is correct.

The most recent documentation is the PDF at https://www.biorxiv.org/content/10.1101/2023.11.21.568164v2 and it says "The R1.fastq and R2.fastq inputs can be replaced with multiple sets of read files listed consecutively, as long as each pair is in order." I hope to put that preprint PDF on an actual documentation website soon.

**Comment by shashkat** [comment]
Thank You so much for your reply @Yenaled! That is very useful!
