### ISSUE TITLE
--umi-gene no longer supported in kb count?

### ISSUE THREAD

**Issue by biobenkj** [pachterlab/kb_python#238]
**Describe the issue**
Is `--umi-gene` no longer a supported option in `kb count`? I don't see it in the help documentation but seem to find it in the `main.py`.

**What is the exact command that was run?**
```
kb count --help
```

Thanks so much!

**Comment by Yenaled** [comment]
Correct, it's no longer an option because it's actually always enabled now for single-cell UMI-based technologies.

**Comment by biobenkj** [comment]
Thanks!
