### ISSUE TITLE
How to run RNA velocity analysis (La Manno) on BAM files

### ISSUE THREAD

**Issue by NikTuzov** [pachterlab/kb_python#240]
Hello Delaney:

Is it possible to run that kind of analysis on BAM files instead of FASTQ?
[Here](https://www.reddit.com/r/bioinformatics/comments/ih4bdk/kallisto_analysis_of_bam_files/?rdt=54029) I found a suggestion to convert BAM to FASTQ as:

samtools collate -n 128 -u -O -@ $threads "$sample.bam" /tmp/bam-to-fastq- \
| samtools fastq -F 0x900 -@ $threads \
    -0 /dev/null \
    -1 "${sample}_1.fastq.gz" \
    -2 "${sample}_2.fastq.gz" \
    -s "$sample.fastq.gz" -

Is this a valid approach?

Regards,
Nik

**Comment by Yenaled** [comment]
Yes, definitely valid -- all it's doing is converting the BAM to FASTQ files, which you can then supply to kallisto.

**Comment by NikTuzov** [comment]
Thank you for a prompt reply.

**Comment by NikTuzov** [comment]
One more question: are there any reservations/concerns if the BAM files are produced by Cell Ranger?

**Comment by Yenaled** [comment]
I don't see a problem with it. As long as they contain the reads, it's fine.
