### ISSUE TITLE
kb ref can't handle blanks in path arguments

### ISSUE THREAD

**Issue by NikTuzov** [pachterlab/kb_python#245]
Hello Delaney:

kb ref (and probably kb count also) cannot find the input files if the paths contain blanks. I have tried double and single quotes, to no avail. Is there a way around that, short of copying the input file(s)?

Regards,
Nik Tuzov

**Comment by Yenaled** [comment]
Ooh, i haven’t looked into it but looks like that’s something that can only be addressed via an update, if true. I’ll make note of it. For now, you have to just create a symlink (ln -s) to the file.

**Comment by NikTuzov** [comment]
Thank you for a

**Comment by NikTuzov** [comment]
Thank you for a fast reply.
