### ISSUE TITLE
Changed barcodes from the kb-python count 

### ISSUE THREAD

**Issue by Alvis-Jiang** [pachterlab/kb_python#249]
Hi, 

I am now using kb python to obtain splice/unsplice count from my 10X V3 single cell RNA sequencing data. It works but when I load the adata.h5ad file in the scVelo, I found that the barcodes in the adata.h5ad are different from the 10X V3 barcode whitelist, they only have about 1000 out of 100000 barcoeds overlapped with the whitelist. Could you kindly give me soem gudiance on solving this issue? Thanks a lot! The below is my command:

` !kb count --h5ad -i /depot/pbaloni/data/Lab_members/Boyu_Jiang/RNA_Volecity/velocity_index/index.idx -g /depot/pbaloni/data/Lab_members/Boyu_Jiang/RNA_Volecity/velocity_index/t2g.txt -x 10xv3 -o $output_folder -t 128 -c1 /depot/pbaloni/data/Lab_members/Boyu_Jiang/RNA_Volecity/velocity_index/cdna_t2c.txt -c2 /depot/pbaloni/data/Lab_members/Boyu_Jiang/RNA_Volecity/velocity_index/intron_t2c.txt --workflow lamanno --filter bustools -t 128 $fastq1 $fastq2
`

Best,
Boyu

**Comment by Yenaled** [comment]
The barcodes in the adata object shouldn't be different from the 10xv3 barcodes... Are you looking at the correct whitelist? You can supply your own custom whitelist file using -w in kb count. Additionally, in the counts_unfiltered directory of your output folder, there should be a file ending in barcodes.txt -- do the barcodes listed there match your whitelist?

**Comment by Alvis-Jiang** [comment]
Hi Yenaled,

Thanks for your reply! You are right, I found that I had used the wrong barcode whitelist of 10XV3, now all barcodes in the adata match the whitelist.

Best,
Boyu
