### ISSUE TITLE
Issue obtaining unaligned reads

### ISSUE THREAD

**Issue by DanLesman** [pachterlab/kb_python#250]
I am interested in separating out my reads that are aligning and not aligning after using kb count. I modified kallisto so that the -n argument is passed. I then run bustools text -f -o bus.txt output.bus to try and see the line numbers of the aligned reads so I can determine which reads are aligning, but every value in the final column is 0. Not sure if I'm doing something wrong, if there is a bug, or if there is a better way  of obtaining the unaligned reads.

Thank you!

**Comment by Yenaled** [comment]
Are you using "kb count"? Try specifying --num instead of -n.

**Comment by DanLesman** [comment]
This works, thank you!
