### ISSUE TITLE
I am having an issue with kb index, it won't take my files (I think ?)

### ISSUE THREAD

**Issue by ashaypatel** [pachterlab/kb_python#260]
I am entering this command:
 kb ref -i index.idx -g t2g.txt -f1 cdna.fasta Homo_sapiens.GRCh38.cdna.all.fa.gz  Homo_sapiens.GRCh38.112.gtf.gz

and I am getting this error:
<img width="1440" alt="Screenshot 2024-07-13 at 9 00 59 AM" src="https://github.com/user-attachments/assets/f891aa14-28fc-4675-967c-06881827cc93">

**Comment by Yenaled** [comment]
You’re using the wrong fasta (.fa.gz) file — you need to supply the GENOME fasta. Look for the primary assembly on ensembl’s website.

**Comment by ashaypatel** [comment]
Also, I used the command (last night):
kb count -x 10XV3 -output_dir -i index.idx -g t2g.txt --batch-barcodes batch.txt

This is what I still have. Am I using the command correctly or is unexpected?

<img width="982" alt="Screenshot 2024-07-14 at 8 12 32 AM" src="https://github.com/user-attachments/assets/ee3ed029-b3dc-4853-9dc5-327a2a086b4f">

**Comment by Yenaled** [comment]
Command looks fine to me. It can take a long time to run if you have a massive sequencing dataset. You can always check if your process is running and utilizing all available threads via htop. Also, next time you run kb count, add --verbose so you can track progress more easily.

**Comment by ashaypatel** [comment]
Thanks!

**Comment by ashaypatel** [comment]
I am running the same command with the verbose flag. Why is it that so few reads are being mapped. Is this okay?
<img width="647" alt="Screenshot 2024-07-14 at 8 32 56 AM" src="https://github.com/user-attachments/assets/048aca51-7973-4588-961e-530bb8613a53">

**Comment by Yenaled** [comment]
That is something i can't answer; low mapping rate is not really a kallisto issue -- it's either something wrong with your data (poor quality) or you are mapping your reads against the wrong thing (e.g. mapping against human when it's mouse, mapping your reads against your current index when you actually have single-nucleus data with lots of introns, etc.).

**Comment by ashaypatel** [comment]
This is single nucleus data? What should I map against?

**Comment by Yenaled** [comment]
For single-nucleus, see the section on single-nucleus here: https://www.biorxiv.org/content/10.1101/2023.11.21.568164v2.full

Also, one more thing, make sure you have your strand-specificity setting set correctly. You might try --strand=unstranded in kb count if you are unsure whether your library is stranded or not.

**Comment by ashaypatel** [comment]
What's the command for kb count (multi-sample analysis using the NAC index type)?

**Comment by Yenaled** [comment]
Same thing, use the --batch-barcodes like you did for the standard index type.

**Comment by ashaypatel** [comment]
Do i need to specify --sum=<sum> if I am using this for downstream analysis with  SEURAT

**Comment by Yenaled** [comment]
Yes

**Comment by ashaypatel** [comment]
Sorry, I am new to this analysis, what would I specify the sum parameter as?

**Comment by Yenaled** [comment]
--sum=total

(After all, you want the total counts; i.e. sum of exons+introns+splice junctions).

**Comment by ashaypatel** [comment]
kb count -x 10XV3 --workflow=nac -o output.dir -i index.idx -g t2g.txt -c1 cdna.txt -c2 nascent.txt --sum=total --batch-barcodes batch.txt --verbose --strand=unstranded

Does this look correct?

**Comment by ashaypatel** [comment]
I'm now getting ~35% mapped instead of 8.4%, is that normal for snRNArnaseq

**Comment by Yenaled** [comment]
I usually see higher percentages (around 60%) — but that’s on my own data. If your data has poor quality, then it could be low.

**Comment by ashaypatel** [comment]
<img width="1033" alt="Screenshot 2024-07-15 at 8 25 40 AM" src="https://github.com/user-attachments/assets/3ed3e0cb-5306-460e-a881-7e0c7065e251">

I assume its the cells_x_genes.total.mtx file that I use for downstream analysis with SEURAT?

**Comment by Yenaled** [comment]
Correct

**Comment by ashaypatel** [comment]
I know this is a SEURAT question but when I run:
seurat_obj<-CreateSeuratObject(counts=expression_matrix,project="SEA_AD_MTG",
                               min.cells = 3, min.features = 200)


I get the error (I don't know why?)
<img width="487" alt="Screenshot 2024-07-15 at 9 19 54 AM" src="https://github.com/user-attachments/assets/543d1201-6f9f-44c5-91d7-b7a72603d4b2">

**Comment by Yenaled** [comment]
Ah sorry, can't answer Seurat issues here, because i don't have the bandwidth to debug Seurat (it's not an error i know about off the top of my head).

**Comment by ashaypatel** [comment]
I assume I loaded it in correclty though?
<img width="577" alt="Screenshot 2024-07-15 at 9 27 17 AM" src="https://github.com/user-attachments/assets/a780fbbb-bdb8-4fde-90a5-a4a29da21d03">

**Comment by ashaypatel** [comment]
And:
<img width="576" alt="Screenshot 2024-07-15 at 9 27 50 AM" src="https://github.com/user-attachments/assets/fcce3a81-e123-4e75-ad8d-2a042ae0e964">

**Comment by Yenaled** [comment]
Yes, at first glance, the ReadMtx looks fine

**Comment by ashaypatel** [comment]
My data is single nuclear RNASeq data from the 10X Multiome. Which tech should I use in kb ref?

**Comment by Yenaled** [comment]
Didn't I already answer that here: https://www.biostars.org/p/9598962/
