### ISSUE TITLE
kb: error: unrecognized arguments: --umi-gene in version 0.28.2

### ISSUE THREAD

**Issue by wlkath** [pachterlab/kb_python#263]
I previously used kb_python about a year ago, version 0.27.3.    The command

kb count -i ../fb653kb/transcriptome.idx -g ../fb653kb/transcripts_to_genes.txt --overwrite -x CELSeq2 --strand forward --umi-gene -o ZT22_20190309_AR01 ../sc/ZT22_20190309_AR01_1.fastq.gz .../sc/ZT22_20190309_AR01_2.fastq.gz

worked fine then.   I am revisiting this data with an updated genome and reference and thought I would upgrade to the newest version (installed via bioconda).    

With the new version I get the error

kb: error: unrecognized arguments: --umi-gene in version 0.28.2

Has the syntax changed?   Or does the --umi-gene option no longer work? 

Thanks!

**Comment by Yenaled** [comment]
You no longer need --umi-gene as it is enabled by default.

**Comment by wlkath** [comment]
Thanks very much for explaining!

**Comment by wlkath** [comment]
One more post to close the issue.
