### ISSUE TITLE
using kb-python with the Takara SMART-Seq mRNA LP (with UMIs) kit

### ISSUE THREAD

**Issue by franziskadenk** [pachterlab/kb_python#267]
Dear Pachter lab, 

First of all, as always, thanks again for providing such a great algorithm and tool for the community! 

I have a bit of an odd question that is probably just down to my ignorance. We have recently run a plate-based sequencing experiment where our collaborators made libraries using the Takara SMART-Seq mRNA LP (with UMIs) kit. Your team previously advised that we should be able to align these reads with -x SMARTSEQ3 and indeed, superficially, that worked very nicely. The code I used is below, with one well as an example. 

The puzzle is what we get downstream. We used 96 well plates, but we get about 3x that many unique barcodes. Now, biologically, it is entirely feasible, if not likely, that we had more than one cell per well, since the neurons we sequenced are clinging very tightly to satellite glia. Moreover, we can see in the data that this is indeed likely what happened, since there are many satellite glial cell transcripts in addition to neuronal ones (which however do not segregate very well into individual clusters). 

What I don't understand is how this actually happens, since in terms of the library preparation, the only barcoding in the SMART-seq mRNA LP protocol is the use of unique dual indexed primers to amplify library material from each well. So each well should only have one barcode. Yesterday, I thought it might have been a silly mistake I made downstream when assembling everything in Seurat, but upon closer inspection of the unfiltered_umi files today, I realised that some wells indeed only have one barcode, but other wells have e.g. four. As an example, well Blad1A1 should have barcode 
CCGC GGTT CTA GC  GCT, but in actual fact the output has: 
CCGC GGTT CTA GC GCT
CCGC GGTT GTA GC GCT
CCGC GGTT TTA GC GCT
TCGC  GGTT CTA GC GCT

Is this due to barcode sequencing errors? Should I apply a white-list to prevent this issue? 

I would be grateful if you could advise. 

Thank you so much and best wishes,
Fran

**What is the exact command that was run?**
kb count --verbose --overwrite --h5ad --gene-names -t 4 -m 4G -i '/scratch/prj/wcard_advseqanlys/FDenk/index.idx' -g '/scratch/prj/wcard_advseqanlys/FDenk/t2g.txt' -x SMARTSEQ3 -o '/scratch/prj/wcard_advseqanlys/FDenk/output_kid2/Kidn2G7/Kidn2G7' R1324-S0004_A94137_Kidn2G7_A22MFCYLT3_CAGATCAA-CGCAGGCA_L006_I1.fastq.gz R1324-S0004_A94137_Kidn2G7_A22MFCYLT3_CAGATCAA-CGCAGGCA_L006_I2.fastq.gz R1324-S0004_A94137_Kidn2G7_A22MFCYLT3_CAGATCAA-CGCAGGCA_L006_R1.fastq.gz R1324-S0004_A94137_Kidn2G7_A22MFCYLT3_CAGATCAA-CGCAGGCA_L006_R2.fastq.gz

**Comment by franziskadenk** [comment]
Actually never mind!! I clearly was not thinking straight when looking at how the plates were sequenced. They were split over several lanes - so this was the reason for all the seemingly odd barcode duplications! 

Thanks again!

**Comment by Yenaled** [comment]
Yes, it is due to barcoding sequencing errors and you will need to provide a so-called whitelist to prevent this issue.

**Comment by franziskadenk** [comment]
Thanks so much for the super-quick clarification, as usual! Have a lovely weekend!
