### ISSUE TITLE
Adding a gene for a custom reference

### ISSUE THREAD

**Issue by eigenP** [pachterlab/kb_python#273]
**Describe the issue**
I'm making a custom reference (for the chicken genome) and I also want to add the GFP sequence. I have successfully done so following the instructions for cellranger (https://www.10xgenomics.com/support/software/cell-ranger/latest/tutorials/cr-tutorial-mr) (and the analysis works as expected with cellranger), but after inspecting the final outputs of kb ref and count, there is no GFP (also no trace of it in t2g.txt, etc.)

Any pointers (e.g. do I need to add more fields in the GFP gtf or FASTA than what the 10x tutorial) would be greatly appreciated! Thank you in advance.

**What is the exact command that was run?**
```
kb ref -i index.idx -g t2g.txt -f1 cdna.fasta --overwrite Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.dna_GFP.toplevel.fa Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.112.filtered.GFP.gtf
```

**Comment by Yenaled** [comment]
You need to put more fields into the GTF. Take a look at an example for another gene and use that as a template for making your custom GTF entry.
