### ISSUE TITLE
ensembl ID to gene symbol for kb output

### ISSUE THREAD

**Issue by zuowulin** [pachterlab/kb_python#52]
Hi there,

I was using the function of ```read_count_output``` in ```BUSpaRse``` to analyze the output of ```kb```.

The output files of ```kb``` is as followed
```cells_x_genes.barcodes.txt  cells_x_genes.genes.txt  cells_x_genes.mtx```

```head``` of ```cells_x_genes.genes.txt``` is as followed
```[counts_unfiltered]$ head cells_x_genes.genes.txt 
ENSG00000243485.5
ENSG00000237613.2
ENSG00000186092.6
ENSG00000238009.6
ENSG00000239945.1
ENSG00000239906.1
ENSG00000241599.1
ENSG00000236601.2
ENSG00000284733.1
ENSG00000235146.2
```
I was able to generate the ```dgCMatrix``` with barcodes in columns and genes in rows. And the gene names in rows are the Ensembl gene ID with version. 

Is there any way to convert the Ensembl gene ID to the gene symbol?

Thank you!

**Comment by Lioscro** [comment]
Hi, @zuowulin,
By gene symbol do you mean the third column in the transcript-to-genes mapping (the argument to `-g` in `kb ref`)?

**Comment by zuowulin** [comment]
Yes, it is.

**Comment by Lioscro** [comment]
Unfortunately, the only way to do that atm is to look up the row in the transcript-to-genes mapping that corresponds to the particular gene id.

**Comment by Lioscro** [comment]
Just as an update, this is planned for the next release.

**Comment by zuowulin** [comment]
Cool, looking forward to the update.

Wulin

Joseph Min <notifications@github.com> 于2020年2月5日周三 下午11:45写道：
