### ISSUE TITLE
Optional parameter to specify the temporal directory

### ISSUE THREAD

**Issue by kokitsuyuzaki** [pachterlab/kb_python#53]
Hi,

Could you add the **--tempdir** option for the command **kb count**?

Although the temporal directory in the python code seems to be hardcoded as "tmp",
https://github.com/pachterlab/kb_python/blob/92feca6a1ce702935348787bd10f41286a1e0c26/kb_python/count.py#L569
there seems not implemented as a argument of the command **kb count**.
https://github.com/pachterlab/kb_python/blob/c0d4230e2d1688db4d80edeb880c019943244a78/kb_python/main.py#L157

In my environment (grid engine), this part might have caused an error;
I tried to perform multiple **kb count** in a common working directory, but some of them were terminated.

I'm not sure but perhaps this is caused because multiple jobs tried to access the same temporal directory (tmp).

After **cd** and **kb count** in each output directory, this type of error has no more occurred.

**Comment by Lioscro** [comment]
Hi, @kokitsuyuzaki, this feature is planned for the next release.
Thanks for the request!
