### ISSUE TITLE
unrecognized "workflow" argument 

### ISSUE THREAD

**Issue by bluejek128** [pachterlab/kb_python#56]
**Describe the issue**
Kb does not appear to generate outputs for RNA velocity. Error indicates an unrecognized argument "workflow", but function still does not return velocity outputs (ie: cDNA_tx_to_capture.txt, introns_tx_to_capture.txt) even when the deprecated argument "lamanno" is used 

**What is the exact command that was run?**
```
kb ref -i transcriptome.idx -g transcripts_to_genes.txt -d human --workflow lamanno -f2 cdna.fa -c1 cDNA_tx_to_capture.txt -c2 introns_tx_to_capture.txt
```

**Command output (with `--verbose` flag)**
```
kb: error: unrecognized arguments: --workflow
```

**Comment by Lioscro** [comment]
Hi, @bluejek128,

What version of `kb` are you running? The `--workflow` argument is only implemented in the `count-kite` branch and is planned for the next official release.
Could you try using the `--lamanno` argument instead until the next version of `kb` is released?

**Comment by rozovr** [comment]
@Lioscro I had this error as well. It comes up if you try to run the commands of the kite tutorial (https://colab.research.google.com/github/pachterlab/kallistobustools/blob/master/notebooks/kb_kite.ipynb) using the default kb-python installed with pip3.
