### ISSUE TITLE
kb count pseudoalign to multiple genes

### ISSUE THREAD

**Issue by AlicePsyche** [pachterlab/kb_python#57]
Hi, 

I read the document and it seems that kb count could support multiple mapping, as mentioned here: https://www.kallistobus.tools/introduction:
`
--mm                  Include reads that pseudoalign to multiple genes.
`
But when I tried to use this, the error says `kb: error: unrecognized arguments: --mm` and I am using `kb_python 0.24.4`

Please let me know if there is anything I missed. Thank you very much for your help in advance.

Best,
Alice

**Comment by basilkhuder** [comment]
I wonder if this feature has been depreciated as I don't see it listed when I run `kb count`
               ```
usage: kb count [-h] [--keep-tmp] [--verbose] -i INDEX -g T2G -x TECHNOLOGY
                [-o OUT] [-w WHITELIST] [-t THREADS] [-m MEMORY] [-c1 T2C]
                [-c2 T2C] [--overwrite] [--lamanno | --nucleus]
                [--filter [{bustools}]] [--loom | --h5ad]
                fastqs [fastqs ...]
```

**Comment by Lioscro** [comment]
Hi, @AlicePsyche,
the `--mm` flag is only supported in the current development branch (`count-kite`) and is planned for the next release.
If you would like to use it, you have to install `kb` with the following command:
```
pip install git+https://github.com/pachterlab/kb_python@count-kite
```
Please keep in mind there may be instabilities when running the development version.

**Comment by AlicePsyche** [comment]
Thanks a lot. Then I will try the count-kite. 

Thank you very much. I have no further questions.

**Comment by LylaAtta123** [comment]
Hi, when I try to install this branch, I get the following error: 

`  WARNING: Did not find branch or tag 'count-kite', assuming revision or ref.
  Running command git checkout -q count-kite
  error: pathspec 'count-kite' did not match any file(s) known to git`

**Comment by kikegoni** [comment]
Hey,

Same happening here... when is the next release planned?

**Comment by Lioscro** [comment]
Hi, @LylaAtta123 and @kikegoni,
`count-kite` has been deprecated and merged into `devel`. We're planning to release a new version this week.

**Comment by Lioscro** [comment]
Closing because `v0.25.0` was just released. Feel free to reopen if there are related issues.
