### ISSUE TITLE
filtered gene count matrix

### ISSUE THREAD

**Issue by mstemmer** [pachterlab/kb_python#68]
Hi,

I was wondering what kind of filtering is actually happening when the --filter bustools flag is applied. Couldn't really find out whats going on and in your example notebooks you just use the unfiltered output. Could you elaborate on that?
Sorry, if this is not the correct platform to ask such questions...

Cheers,
Manuel.

**Comment by Lioscro** [comment]
Hi, @mstemmer,

Quite a few things happen under the hood.
First, `bustools whitelist` is run, which detects a barcode count threshold based on the first 200 to 100200 BUS records and generates a whitelist of barcodes that will be considered true "cells."
Then, `bustools correct` is run with the newly generated whitelist to filter for the barcodes aforementioned.
Finally, `bustools count` is run to generate a cells by gene matrix containing gene counts.

You can read what each of these commands do in more detail here: https://bustools.github.io/manual
