### ISSUE TITLE
Issues with count-kite?

### ISSUE THREAD

**Issue by seanken** [pachterlab/kb_python#74]
I tried reinstalling count-kite (want to analyze nuclei data) using the command in the kb tutorial:

```
pip install git+https://github.com/pachterlab/kb_python@count_kite
```

But got the error:

```
Cloning https://github.com/pachterlab/kb_python (to revision count-kite) to /tmp/18804074.1.interactive/pip-req-build-5agd4eia
  Running command git clone -q https://github.com/pachterlab/kb_python /tmp/18804074.1.interactive/pip-req-build-5agd4eia
  WARNING: Did not find branch or tag 'count-kite', assuming revision or ref.
  Running command git checkout -q count-kite
  error: pathspec 'count-kite' did not match any file(s) known to git.
```

Looking at the kb_python github can't seem to find the count_kite branch. Trying to figure out what is going on--is it an issue on my end or something else?

**Comment by skannan4** [comment]
It looks like that branch is gone, because I don't find it on the github. I'd like it too, since as far as I can tell I can't access the -n parameter for kb index outside that branch (and need it to build a velocity index locally with my memory constraints).

**Comment by likejie** [comment]
same issue. Any suggestion? Thanks!

**Comment by sbooeshaghi** [comment]
Try installing the latest release 0.25.0.
