### ISSUE TITLE
How to use multiple indices for RNA velocity?

### ISSUE THREAD

**Issue by skannan4** [pachterlab/kb_python#79]
Apologies as this isn't so much an issue as I'm a bit confused. I followed this vignette for generating custom indices for RNA velocity (https://colab.research.google.com/github/pachterlab/kallistobustools/blob/master/notebooks/kb_velocity_index.ipynb#scrollTo=eghgsyNlxZGj). I am using the devel branch of kb_python 0.24.4. I generated 8 indices (as opposed to 4 in the vignette) just for memory reasons - the first is labeled .idx_cdna, and the remaining seven are .idx_intron.x, where x is a number from 0 to 6.

I'm confused on how to proceed with multiple indices for kb count, however. Loading multiple indices to the -i flag didn't seem to work (-i mouse_velocity.idx_*), and using multiple -i flags only used the last index. I'm not fully sure how the indexing is done under the hood, but should just run kb count with each index individually and then concatenate? I wasn't sure if this would affect UMI collapsing, for example.

**Comment by skannan4** [comment]
Just as an update - I can't run on each index individually because the downstream steps of kb count will throw an error when one of the matrices (spliced or unspliced, depending on whether the cdna or the intron index are used) is empty.

**Comment by skannan4** [comment]
As answered by authors offline: comma separated list with no spaces e.g. -i index.idx_0,index.idx_1,index.idx2... works.

**Comment by winni2k** [comment]
Thanks for the link to the notebook!
