### ISSUE TITLE
Create transcriptome index for both coding and non-coding genes

### ISSUE THREAD

**Issue by kikegoni** [pachterlab/kb_python#85]
Hey,

First, thanks a lot for implementing this software, it is super helpful.

I am trying to build the transcriptome index for hg38 and I was wondering whether it would include the different transcripts for both coding and non-coding genes or if it is only generating the index file considering protein coding genes. 

Specifically I have run
```
kb ref -d human -i <index.idx> -g <t2g.txt>
```

Does the output index.idx include the indexes for coding and non-coding genes?

Thanks in advance,

Best,

Kike

**Comment by Lioscro** [comment]
Hi, @kikegoni,
`kb` will build a transcriptome from all GTF annotations that contain a `transcript` and at least one `exon` feature. I believe all the non-coding genes listed in the Ensembl GTF specification (http://uswest.ensembl.org/info/genome/genebuild/ncrna.html) do have `transcript` and `exon` features in the GTF, so they will be included in the index.
