### ISSUE TITLE
Cannot build index using the fasta file with "chr"

### ISSUE THREAD

**Issue by kepbod** [pachterlab/kb_python#89]
**Describe the issue**
If I tried to build index using genome fasta files downloaded from UCSC and the GENCODE gene annotation gtf file, it produced empty index files. When I removed all "chr" in the fasta and gtf files, it works. If you can consider adding support for files with chromosomes written as "chrXX", that would be great.

**Comment by Lioscro** [comment]
Hi, @kepbod,
`kb` matches the chromosomes in the reference FASTA and GTF by their full strings, so you will have to either add or remove any prefixes (i.e. `chr`) so that they all match. We can look into adding an option to `kb ref` to specify (and ignore) prefixes.
