### ISSUE TITLE
barcode swapping?

### ISSUE THREAD

**Issue by MikeHala** [pachterlab/kb_python#90]
Dear all,

Is there an existing solution based on the kb output for identification of swapped barcodes across samples 
(e.g. https://www.nature.com/articles/s41467-018-05083-x/)? 
DropletUtils::swappedDrops provides one based on CellRanger's output, but it seems to me it cannot be readily applied to kb output (see Aaron Lun's reply at https://support.bioconductor.org/p/p133254/). 

Kind regards,
Mike

```
time kb count \
-i ${KALLISTO_RESOURCE}/transcriptome.idx \
-g ${KALLISTO_RESOURCE}/transcripts_to_genes.txt \
-x 10xv3 --verbose -o ${WORK_DIR}/kallisto_output/ \
${FASTQ_DIR}/*.fastq.gz
```

**Comment by Lioscro** [comment]
Hi, @MikeHala,
Does DropletUtils take CellRanger count matrix as output? If so, you can try providing `kb count` with the `--cellranger` option, which will output the matrix as CellRanger-compatible format.
