### ISSUE TITLE
Error in merging bus records in kb count

### ISSUE THREAD

**Issue by maddemaddi** [pachterlab/kb_python#92]
Hi!

I am currently learning how to use kb ref and kb count to be able to perform scRNA velocity analysis with scvelo. The code works otherwise perfectly, but an error occurs every time in the step of merging bus records. This is the code I have been using for the counting:

> !kb count --h5ad -i index.idx.cdna, index.idx_intron.0, index.idx_intron.1, index.idx_intron.2, index.idx_intron.3, index.idx_intron.4, index.idx_intron.5, index.idx_intron.6 \
-g t2g.txt -x 10xv2 -o H22\
-c1 spliced_t2c.txt -c2 unspliced_t2c.txt --workflow lamanno --filter bustools -t 2 \
H22_HFD_5d_S21_L001_R1_001.fastq.gz \
H22_HFD_5d_S21_L001_R2_001.fastq.gz

And the output looks like this:

> [2020-12-08 16:00:30,178] WARNING Multiple indices were provided. Aligning to split indices is currently EXPERIMENTAL and results in loss of reads. It is recommended to use a single index until this feature is fully supported. Use at your own risk!
> [2020-12-08 16:00:30,178]    INFO Generating BUS file using 8 indices
> [2020-12-08 16:00:30,178]    INFO Using index index.idx.cdna to generate BUS file to H22/tmp/bus_part0 from
> [2020-12-08 16:00:30,178]    INFO         H22_HFD_5d_S21_L001_R1_001.fastq.gz
> [2020-12-08 16:00:30,178]    INFO         H22_HFD_5d_S21_L001_R2_001.fastq.gz
> [2020-12-08 16:02:08,187]    INFO Sorting BUS file H22/tmp/bus_part0/output.bus to /Users/lackmama/Desktop/scvelo5/H22/tmp/tmplxak7mqk
> [2020-12-08 16:02:12,964]    INFO Using index index.idx_intron.0 to generate BUS file to H22/tmp/bus_part1 from
> [2020-12-08 16:02:12,965]    INFO         H22_HFD_5d_S21_L001_R1_001.fastq.gz
> [2020-12-08 16:02:12,965]    INFO         H22_HFD_5d_S21_L001_R2_001.fastq.gz
> [2020-12-08 16:04:55,613]    INFO Sorting BUS file H22/tmp/bus_part1/output.bus to /Users/lackmama/Desktop/scvelo5/H22/tmp/tmp624o_rum
> [2020-12-08 16:04:57,691]    INFO Using index index.idx_intron.1 to generate BUS file to H22/tmp/bus_part2 from
> [2020-12-08 16:04:57,691]    INFO         H22_HFD_5d_S21_L001_R1_001.fastq.gz
> [2020-12-08 16:04:57,691]    INFO         H22_HFD_5d_S21_L001_R2_001.fastq.gz
> [2020-12-08 16:07:38,282]    INFO Sorting BUS file H22/tmp/bus_part2/output.bus to /Users/lackmama/Desktop/scvelo5/H22/tmp/tmp8dldfqyk
> [2020-12-08 16:07:40,419]    INFO Using index index.idx_intron.2 to generate BUS file to H22/tmp/bus_part3 from
> [2020-12-08 16:07:40,419]    INFO         H22_HFD_5d_S21_L001_R1_001.fastq.gz
> [2020-12-08 16:07:40,419]    INFO         H22_HFD_5d_S21_L001_R2_001.fastq.gz
> [2020-12-08 16:10:17,469]    INFO Sorting BUS file H22/tmp/bus_part3/output.bus to /Users/lackmama/Desktop/scvelo5/H22/tmp/tmpj2_npgbv
> [2020-12-08 16:10:19,550]    INFO Using index index.idx_intron.3 to generate BUS file to H22/tmp/bus_part4 from
> [2020-12-08 16:10:19,550]    INFO         H22_HFD_5d_S21_L001_R1_001.fastq.gz
> [2020-12-08 16:10:19,550]    INFO         H22_HFD_5d_S21_L001_R2_001.fastq.gz
> [2020-12-08 16:12:58,836]    INFO Sorting BUS file H22/tmp/bus_part4/output.bus to /Users/lackmama/Desktop/scvelo5/H22/tmp/tmptxxr9sx8
> [2020-12-08 16:13:01,016]    INFO Using index index.idx_intron.4 to generate BUS file to H22/tmp/bus_part5 from
> [2020-12-08 16:13:01,016]    INFO         H22_HFD_5d_S21_L001_R1_001.fastq.gz
> [2020-12-08 16:13:01,016]    INFO         H22_HFD_5d_S21_L001_R2_001.fastq.gz
> [2020-12-08 16:15:43,316]    INFO Sorting BUS file H22/tmp/bus_part5/output.bus to /Users/lackmama/Desktop/scvelo5/H22/tmp/tmp72sn8l46
> [2020-12-08 16:15:45,361]    INFO Using index index.idx_intron.5 to generate BUS file to H22/tmp/bus_part6 from
> [2020-12-08 16:15:45,361]    INFO         H22_HFD_5d_S21_L001_R1_001.fastq.gz
> [2020-12-08 16:15:45,361]    INFO         H22_HFD_5d_S21_L001_R2_001.fastq.gz
> [2020-12-08 16:18:23,235]    INFO Sorting BUS file H22/tmp/bus_part6/output.bus to /Users/lackmama/Desktop/scvelo5/H22/tmp/tmp5ar_yaoi
> [2020-12-08 16:18:25,443]    INFO Using index index.idx_intron.6 to generate BUS file to H22/tmp/bus_part7 from
> [2020-12-08 16:18:25,443]    INFO         H22_HFD_5d_S21_L001_R1_001.fastq.gz
> [2020-12-08 16:18:25,443]    INFO         H22_HFD_5d_S21_L001_R2_001.fastq.gz
> [2020-12-08 16:21:11,127]    INFO Sorting BUS file H22/tmp/bus_part7/output.bus to /Users/lackmama/Desktop/scvelo5/H22/tmp/tmpy29yy5h9
> [2020-12-08 16:21:13,165]    INFO Mashing BUS records to H22 from
> [2020-12-08 16:21:13,165]    INFO         H22/tmp/bus_part0
> [2020-12-08 16:21:13,165]    INFO         H22/tmp/bus_part1
> [2020-12-08 16:21:13,165]    INFO         H22/tmp/bus_part2
> [2020-12-08 16:21:13,165]    INFO         H22/tmp/bus_part3
> [2020-12-08 16:21:13,165]    INFO         H22/tmp/bus_part4
> [2020-12-08 16:21:13,165]    INFO         H22/tmp/bus_part5
> [2020-12-08 16:21:13,165]    INFO         H22/tmp/bus_part6
> [2020-12-08 16:21:13,165]    INFO         H22/tmp/bus_part7
> [2020-12-08 16:22:15,564]    INFO Sorting BUS file H22/mashed.bus to /Users/lackmama/Desktop/scvelo5/H22/tmp/tmp3uisw2bq
> [2020-12-08 16:22:25,219]    INFO Merging BUS records in H22/mashed.bus to H22
> [2020-12-08 16:23:20,468]   ERROR An exception occurred
> Traceback (most recent call last):
>   File "/Users/lackmama/miniconda3/lib/python3.8/site-packages/kb_python/main.py", line 785, in main
>     COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
>   File "/Users/lackmama/miniconda3/lib/python3.8/site-packages/kb_python/main.py", line 195, in parse_count
>     count_velocity(
>   File "/Users/lackmama/miniconda3/lib/python3.8/site-packages/kb_python/count.py", line 1450, in count_velocity
>     bus_result = kallisto_bus_split(
>   File "/Users/lackmama/miniconda3/lib/python3.8/site-packages/kb_python/count.py", line 228, in kallisto_bus_split
>     merge_result = bustools_merge(
>   File "/Users/lackmama/miniconda3/lib/python3.8/site-packages/kb_python/validate.py", line 124, in inner
>     validate(arg)
>   File "/Users/lackmama/miniconda3/lib/python3.8/site-packages/kb_python/validate.py", line 85, in validate
>     VALIDATORS[ext](path)
>   File "/Users/lackmama/miniconda3/lib/python3.8/site-packages/kb_python/validate.py", line 40, in validate_bus
>     raise FileVerificationFailed('{} has no BUS records'.format(path))
> kb_python.validate.FileVerificationFailed: H22/merged.bus has no BUS records

What would be the best solution for tackling this issue?

Thanks in advance! :)

Br,
Madeleine

**Comment by Lioscro** [comment]
Hi, @maddemaddi,
I suspect this is due to the highly experimental nature of using split indices. There is a bug (for lack of a better term; closer to due to implementation details) that causes the loss of BUS records when merging. We are working on a fix, but it requires a larger restructuring of the codebase in kallisto and bustools and so will take a while till we get to it.

Is there any way you can try running with a single index? You may need to run on a server due to memory requirements.

**Comment by lakigigar** [comment]
Hi Madelein, 

Just to clarify, we have recently updated the split-merge feature and fixed some previous issues with it, which are not yet integrated into kb. Probably the best is to wait for the next release, or else work directly within the kallisto and bustools commands. RNA velocity with a single index should not require a "server" though, we regularly run the Linarsson index and even have a Google Colab notebook for it: https://colab.research.google.com/github/pachterlab/kallistobustools/blob/master/notebooks/RNA_velocity_lamanno.ipynb

**Comment by kullrich** [comment]
Same issue on version v0.27.0

Working on a 30GB genome needs me to split the index, which worked fine.

Anyhow, if I can not work with split indexes and kb-python, could you please directly indicate also on your tutorials to NOT use it until it is made stable, please.

Thank you in anticipation
